version: '3'

services:
  app:
    build: .
    restart: always
    command: python app.py
    container_name: py1337x_downloader
    network_mode: "host"
    environment:
      - TRANSMISSION_IP=192.168.1.100
      - TRANSMISSION_PORT=9091
    volumes:
      - .:/app
      - download_history:/app/download_history

volumes:
  download_history: